### ISSUE TITLE
Fix: Movement Feedback (v2)

### ISSUE THREAD

**Issue by SalaheddineZ** [SillyBusinessInc/SillyBusinessGame#100]
1. INCREASE GRAVITY/MASS, MAKING THE PLAYER RETURN TO THE GROUND QUICKER WHILE KEEPING THE CURRENT JUMP HEIGHT
2. REMOVE SLIDING/SKIDDING/GROUND MOMENTUM, MAKING THE PLAYER STOP WHEN THEY RELEASE DIRECTIONAL INPUT
3. EITHER USE FIXED_UPDATE or DELTA TIME,  IN EITHER CASE, IT SHOULD NOT BE FRAMERATE DEPENDENT

**Comment by WantToBeeMe** [comment]
Is just just improving the mass? I am unsure though.
Also, if this is the case, dont forget to also improve the jump force again
