### ISSUE TITLE
Tail upgrades

### ISSUE THREAD

**Issue by SalaheddineZ** [SillyBusinessInc/SillyBusinessGame#106]
Add the possibility so that designers can upgrade a tail, depended on [#105](https://github.com/SillyBusinessInc/SillyBusinessGame/issues/105)

- Attacking Speed
- Attack Damage

**Comment by WantToBeeMe** [comment]
![Image](https://github.com/user-attachments/assets/68b9a3d3-c143-4dc0-911f-8c9fe9de8d39)
