### ISSUE TITLE
Melee enemies

### ISSUE THREAD

**Issue by SalaheddineZ** [SillyBusinessInc/SillyBusinessGame#107]
* Follow enemy should not have a vision at all
* It should always agro on the player
* It simply checks the distance, and only tries to walk to the enemy
* Make the telegraph better

**Comment by PimMiii** [comment]
![Image](https://github.com/user-attachments/assets/ffc2156a-4476-4bb1-bde5-a871bc9dcce2)
I think this should mostly be what we need state-wise
