### ISSUE TITLE
Player healthbar

### ISSUE THREAD

**Issue by WantToBeeMe** [SillyBusinessInc/SillyBusinessGame#12]
BLOCKED BY: https://github.com/SillyBusinessInc/SillyBusinessGame/issues/7

The player should have a health bar. If it reach 0 you are dead.
You then can just respawn on a designated spawn platform (which you spawn also at the start of the game)

**Comment by PimMiii** [comment]
Just realized i never made any attack for the #11 , oopsie.
So i'll implement an attack for it in this ticket.

**Comment by PimMiii** [comment]
@WantToBeeMe updated.
AttackCooldown is now the time before enemy goes back into FollowingState
