### ISSUE TITLE
Door controller

### ISSUE THREAD

**Issue by WantToBeeMe** [SillyBusinessInc/SillyBusinessGame#38]
Door controller:
- Change the looks of the door
(currently just a wall/recatangle)
- if its locked/unlocked
- door prefab 
- connect a room to it 
 

**Dependent on interactable ticket to fully finish, startable though**

**Comment by PimMiii** [comment]
Made some functionality, to finish this ticket fully we'd need Room system (#40) / loader, and Interactable class (#36) finished.

There is a door prefab, it has a simple opening animation that can be expanded on by Art/Design, the door's material is changed on lock/unlock, and it has a reference to a Scene if null the door gets disabled and doesnt show up.
